
new_variables:
   ### [format] name: formula
   ### can use functions from `math`, `np` (numpy), and `awkward` in the expression

   #Mask pt < 0.1
   #fjet_clus_pt!=-999
   #fjet_clus_pt>0.1

   ### Kinematic variables
   part_px: fjet_clus_pt*np.cos(fjet_clus_phi)
   part_py: fjet_clus_pt*np.sin(fjet_clus_phi)
   part_pz: fjet_clus_pt*np.sinh(fjet_clus_eta)
   part_pt: fjet_clus_pt
   part_pt_log: np.log(fjet_clus_pt)
   part_e_log: np.log(fjet_clus_E)
   part_logptrel: np.log(fjet_clus_pt/jet_pt[:,np.newaxis])
   part_logerel: np.log(fjet_clus_E/jet_energy[:,np.newaxis])
   part_d0_tanh: np.tanh(fjet_clus_d0)
   part_z0_tanh: np.tanh(fjet_clus_z0) 
   ###part_logptrel: np.log(fjet_clus_pt)
   ###part_logerel: np.log(fjet_clus_E)
   #part_deltaR: np.hypot(fjet_clus_eta, fjet_clus_phi)
   test_w: fjet_testing_weight_pt
   part_deltaR: np.hypot(fjet_clus_deltaeta, fjet_clus_deltaphi)
   part_mask: part_pt_log>0.1
   #part_mask: ak.ones_like(fjet_clus_pt)

preprocess:
  ### method: [manual, auto] - whether to use manually specified parameters for variable standardization
  method: manual
  ### data_fraction: fraction of events to use when calculating the mean/scale for the standardization
  data_fraction: 1.0

inputs:
   pf_points:
      length: 80
      pad_mode: wrap
      vars:
         - [fjet_clus_deltaeta]
         - [fjet_clus_deltaphi]
   pf_features:
      length: 80
      pad_mode: wrap
      vars:
      ### [format 1]: var_name (no transformation)
      ### [format 2]: [var_name,
      ###              subtract_by(optional, default=None, no transf. if preprocess.method=manual, auto transf. if preprocess.method=auto),
      ###              multiply_by(optional, default=1),
      ###              clip_min(optional, default=-5),
      ###              clip_max(optional, default=5),
      ###              pad_value(optional, default=0)]

         - [part_pt_log]
         - [part_e_log]
         - [part_logptrel]
         - [part_logerel]
         - [part_deltaR]
         - [fjet_clus_deltaeta]
         - [fjet_clus_deltaphi]
         # - [part_d0_tanh, null]
         # - [part_z0_tanh, null]
         # - [fjet_clus_d0_uncertainty, null]
         # - [fjet_clus_z0_uncertainty, null]
   pf_vectors:
      length: 80
      pad_mode: wrap
      vars:
         - [part_px, null]
         - [part_py, null]
         - [part_pz, null]
         - [fjet_clus_E, null]
   pf_mask:
      length: 80
      pad_mode: constant
      vars:
         - [part_mask, null]

labels:
   value: [label_QCD, label_WZ, label_top, label_higgs]

observers:
   - weight
   - fjet_pt
   # - test_w
   #- jet_energy

weights:
    weight_names: [weight]
